
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = ["http://localhost:8080", "http://localhost:1234", "https://groovymovieapp.netlify.app", "https://65ba963648c2cd070741af4b--charming-crisp-c45fc4.netlify.app"]
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"


[[redirects]]
  from = "/*"
  to = "/"
  status = 200